import { CommonModule } from '@angular/common';
import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { ApiService } from '../core/api.service';
interface Issue { id: string; issueNumber: number; title: string; description?: string; type: number; status: number; priority: number; assigneeId?: string; }
interface Column { status: number; name: string; }
@Component({ standalone: true, imports: [CommonModule, FormsModule], template: `<section><div class="board-header"><div><h1>Kanban board</h1><p>Project {{ projectId }}</p></div><input [(ngModel)]="filter" (ngModelChange)="load()" placeholder="Filter issues"></div><div class="board"><article class="column" *ngFor="let column of columns" (dragover)="$event.preventDefault()" (drop)="drop(column.status)"><h2>{{ column.name }} <span>{{ byStatus(column.status).length }}</span></h2><div class="issue-card" *ngFor="let issue of byStatus(column.status)" draggable="true" (dragstart)="dragged = issue"><strong>#{{ issue.issueNumber }} {{ issue.title }}</strong><small>Priority {{ issue.priority }}</small></div></article></div></section>` })
export class BoardComponent { private readonly api = inject(ApiService); private readonly route = inject(ActivatedRoute); readonly columns: Column[] = [{ status: 1, name: 'Backlog' }, { status: 2, name: 'Todo' }, { status: 3, name: 'In progress' }, { status: 4, name: 'In review' }, { status: 5, name: 'Done' }, { status: 6, name: 'Cancelled' }]; projectId = ''; issues: Issue[] = []; filter = ''; dragged?: Issue; constructor() { this.projectId = this.route.snapshot.paramMap.get('projectId') ?? ''; this.load(); } load() { if (!this.projectId) return; this.api.get<{ items: Issue[] }>(`/projects/${this.projectId}/issues?search=${encodeURIComponent(this.filter)}&page=1&pageSize=100`).subscribe(result => this.issues = result.items); } byStatus(status: number) { return this.issues.filter(issue => issue.status === status); } drop(status: number) { const issue = this.dragged; this.dragged = undefined; if (!issue || issue.status === status) return; this.api.put<void>(`/issues/${issue.id}`, { title: issue.title, description: issue.description, type: issue.type, status, priority: issue.priority, assigneeId: issue.assigneeId ?? null }).subscribe(() => this.load()); } }
