import { CommonModule } from '@angular/common';
import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { ApiService } from '../core/api.service';
interface Sprint { id: string; name: string; goal?: string; status: number; issueCount: number; startDateUtc?: string; endDateUtc?: string; }
interface BacklogIssue { id: string; issueNumber: number; title: string; priority: number; }
@Component({ standalone: true, imports: [CommonModule, FormsModule], template: `<section><h1>Sprints</h1><div class="toolbar"><input [(ngModel)]="name" placeholder="Sprint name"><input [(ngModel)]="goal" placeholder="Sprint goal"><button (click)="create()">Create sprint</button></div><div class="card-grid"><article class="card" *ngFor="let sprint of sprints"><h2>{{ sprint.name }}</h2><p>{{ sprint.goal || 'No goal' }}</p><p>Status: {{ statusName(sprint.status) }} · {{ sprint.issueCount }} issues</p><button *ngIf="sprint.status === 1" (click)="start(sprint.id)">Start</button><button *ngIf="sprint.status === 2" (click)="complete(sprint.id)">Complete</button><button *ngIf="sprint.status === 1" (click)="remove(sprint.id)">Delete</button></article></div><article class="card"><h2>Backlog</h2><p *ngIf="!backlog.length">No unassigned issues.</p><div *ngFor="let issue of backlog" class="toolbar"><span>#{{ issue.issueNumber }} {{ issue.title }}</span><select [(ngModel)]="assignment[issue.id]"><option value="">Choose sprint</option><option *ngFor="let sprint of sprints" [value]="sprint.id">{{ sprint.name }}</option></select><button (click)="assign(issue.id)">Add</button></div></article></section>` })
export class SprintsComponent { private readonly api = inject(ApiService); private readonly route = inject(ActivatedRoute); projectId = ''; sprints: Sprint[] = []; backlog: BacklogIssue[] = []; assignment: Record<string, string> = {}; name = ''; goal = ''; constructor() { this.projectId = this.route.snapshot.paramMap.get('projectId') ?? ''; this.load(); } load() { this.api.get<Sprint[]>(`/projects/${this.projectId}/sprints`).subscribe(value => this.sprints = value); this.api.get<BacklogIssue[]>(`/projects/${this.projectId}/backlog`).subscribe(value => this.backlog = value); } create() { if (!this.name.trim()) return; this.api.post<Sprint>(`/projects/${this.projectId}/sprints`, { name: this.name, goal: this.goal, startDateUtc: null, endDateUtc: null }).subscribe(() => { this.name = ''; this.goal = ''; this.load(); }); } start(id: string) { this.api.post<void>(`/sprints/${id}/start`, {}).subscribe(() => this.load()); } complete(id: string) { this.api.post<void>(`/sprints/${id}/complete`, {}).subscribe(() => this.load()); } remove(id: string) { this.api.put<void>(`/sprints/${id}`, {}).subscribe(() => this.load()); } assign(issueId: string) { const sprintId = this.assignment[issueId]; if (sprintId) this.api.put<void>(`/sprints/${sprintId}/issues/${issueId}`, {}).subscribe(() => this.load()); } statusName(status: number) { return ['','Planned','Active','Completed','Cancelled'][status] ?? 'Unknown'; } }
